version: '3.1'

services:
    python:
        build:
            context: .
            dockerfile: Dockerfile-Python
        command: bash -c 'tail -f /dev/null'
        restart: always
        volumes:
            - .:/code
        container_name: python
